#!/home/ec2-user/.nvm/versions/node/v6.14.1/bin/node

let request = require("request");
let Phrase = require("mmosru-palindrome");
let url = 'https://cdn.learnenough.com/phrases.txt';

request(url, function(error, response, body) {
  let lines = body.split("\n");
  let palindromes = lines.filter(line => (new Phrase(line)).palindrome() );
  
  palindromes.forEach(function(palindrome)  {
    console.log("palindrome detected:", palindrome)
  });
});