#!/home/ec2-user/.nvm/versions/node/v6.14.1/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
// Userful for text-to-speach, or other pure text applications

let url = process.argv[2];

if ( url ) {

  let request = require("request");

  const jsdom = require("jsdom");
  const { JSDOM } = jsdom;

  request(url, function(error, response, body) {
    // Simulate a Document Object Model.
    let { document } = (new JSDOM(body)).window;
  
    // Grab all paragraphs & references
    let paragraphs = document.querySelectorAll("p");
    let references = document.querySelectorAll(".reference");
  
    // Remove references
    references.forEach(function(reference) {
      reference.remove();
    });
  
    // Print out all the paragraphs
    paragraphs.forEach(function(paragraph) {
      console.log(paragraph.textContent + "\n");
    });
  });
} else
  console.log("url missing or invalid.");
